### ISSUE TITLE
PKCS12 keystore

### ISSUE THREAD

**Issue by samarthya** [pavlo-v-chernykh/keystore-go#39]
> keystore.New()

It is a convenient way of initializing, but is there a way to configure for a PKCS#12 based `Keystore`?  Or may be to convert without utilizing another lib/utility to do the same. #

**Comment by pavlo-v-chernykh** [comment]
@samarthya, hi. Thanks for your interest.

Please, take a look at this issue where PKCS#12 vs. JKS discussion took place #37

**Comment by samarthya** [comment]
@pavlo-v-chernykh Thank you for the quick response.
