### ISSUE TITLE
"got invalid digest" with JKS file that doesn't have a password

### ISSUE THREAD

**Issue by marcoacsilva** [pavlo-v-chernykh/keystore-go#40]
Hello.
I'm using a pre-existent JKS file, used in a Java application, to get read by a go application.
This JKS keystore doesn't have a password. I can read it using keytool:

```
*****************  WARNING WARNING WARNING  *****************
* L'intégrité des informations stockées dans votre fichier de clés  *
* n'a PAS été vérifiée. Pour cela, *
* vous devez fournir le mot de passe de votre fichier de clés.                  *
*****************  WARNING WARNING WARNING  *****************

Type de fichier de clés : jks
Fournisseur de fichier de clés : SUN

Votre fichier de clés d'accès contient 1 entrée

Nom d'alias : test
Date de création : 6 août 2021
Type d'entrée : PrivateKeyEntry
...
```

When I try to read it using the lib, I got the "got invalid digest" error.
```
f, err := os.Open(conf.KeystorePath)
	if err != nil {
		return nil, err
	}

	defer func() {
		if err := f.Close(); err != nil {
			panic(err)
		}
	}()

	ks := keystoregov4.New()
	if err := ks.Load(f, pass); err != nil { //got invalid digest here
		return nil, err
	}
}
```

I've tried with pass = nil and with pass being a 0 byte array.

**Comment by anubhav21sharma** [comment]
Facing the same issue with keystores having no set password.
@pavlo-v-chernykh - Can you please check this? Thank you!

**Comment by pavlo-v-chernykh** [comment]
@anubhav21sharma hi. If it is possible, would you mind sharing with me JKS file?

**Comment by anubhav21sharma** [comment]
Ah this is really embarrassing. Its turns out that the jks file I was supplying to keystore-go and the jks file I was testing using keytool are two different files. I was supplying empty password for the keystore that has some password set. :(

I didn't see any issues with the jks which actualyl has no password. Really sorry about the confusion.

**Comment by pavlo-v-chernykh** [comment]
@anubhav21sharma no problem. I'm glad you resolved your issue.
