### ISSUE TITLE
Cant extract Certificates from JKS, if they are not in a CA-Chain, or bound to a private Key

### ISSUE THREAD

**Issue by the-hotmann** [pavlo-v-chernykh/keystore-go#46]
I will provide examples attached to this issue, so everyone can reproduce. (ALWAYS remove the tailing `.txt` from all files you download!)

Just like you have seen in my previous threat https://github.com/pavlo-v-chernykh/keystore-go/issues/44 I loop through the JKS and extract all the entries.

But as a JKS is just a collection of CA-Certs, Certs and Keys it can contain them in nearly all orders and in mostly all combinations.
I think I just catched another combination, that is not handelable with this package currently.

What did I do?

1. download the current Cert-Chain from www.google.de: [www.google.de.pem.txt](https://github.com/pavlo-v-chernykh/keystore-go/files/13579379/www.google.de.pem.txt)
2. convert it to a default JKS, without the chain, but all Certs as seperate entries: 
[www.google.de.jks.txt](https://github.com/pavlo-v-chernykh/keystore-go/files/13579392/www.google.de.jks.txt)
this is the structure of the file:
- CA-CERT
- CERT
- CERT

3. try to loop though the JKS with this package and print out, as what which alias/entry was detected.
4. you will just get the CA-Cert entry, as there is no `isCertEntry` function is missing.

So this request basically asks for the extension of this package so even entries which are plain Certs, (or Cert-Chains!) can be detected.
All those entries are passwordless and shall not be able to take a password, as Certs (and Cert-Chains) are public.

Thanks in advance, I hope I could explain it good enough, so it is understandable :)

I am open for discussion and also open for providing more, if there is a need.

P.S.: please always remove the `.txt` file-extension from all files you download here, as they are not TXTs, but otherwise I can not upload the, as `.pem` & `.jks` are not supported by GitHub.

**Comment by pavlo-v-chernykh** [comment]
Hi @the-hotmann 
I downloaded the `www.google.de.jks` provided by you and found only 3 items in there. All of them are accessible using the library. I do not understand what Kind of functionality you are missing.
```golang
ppackage main

import (
	"crypto/x509"
	"log"
	"os"
	"strings"

	"github.com/pavlo-v-chernykh/keystore-go/v4"
)

func readKeyStore(filename string, password []byte) keystore.KeyStore {
	f, err := os.Open(filename)
	if err != nil {
		log.Fatal(err)
	}

	defer func() {
		if err := f.Close(); err != nil {
			log.Fatal(err)
		}
	}()

	ks := keystore.New()
	if err := ks.Load(f, password); err != nil {
		log.Fatal(err) //nolint: gocritic
	}

	return ks
}

func main() {
	ks := readKeyStore("/Users/pavlo/Downloads/www.google.de.jks", nil)

	for _, a := range ks.Aliases() {
		if ks.IsTrustedCertificateEntry(a) {
			tce, err := ks.GetTrustedCertificateEntry(a)
			if err != nil {
				log.Fatal(err)
			}

			cert, err := x509.ParseCertificates(tce.Certificate.Content)
			if err != nil {
				log.Fatal(err)
			}

			log.Printf("%s: %s", strings.TrimSpace(a), cert[0].Subject)
		} else if ks.IsPrivateKeyEntry(a) {
			log.Fatal("private key entry detected")
		}
	}
}
```

Stdout:
```
2023/12/09 11:07:40 www.google.de3: CN=GTS Root R1,O=Google Trust Services LLC,C=US
2023/12/09 11:07:40 www.google.de: CN=www.google.de
2023/12/09 11:07:40 www.google.de2: CN=GTS CA 1C3,O=Google Trust Services LLC,C=US
```

Attached debug view and entries view from KeyStore Explorer
<img width="537" alt="Screenshot 2023-12-09 at 11 12 15" src="https://github.com/pavlo-v-chernykh/keystore-go/assets/526266/e4ed8bbd-4b11-4b66-b1f0-0e9da8609ed9">
<img width="1248" alt="Screenshot 2023-12-09 at 11 11 19" src="https://github.com/pavlo-v-chernykh/keystore-go/assets/526266/dbce3988-eb57-41b7-a9f4-b9e7472d1ba7">
